version: '3.8'

services:

  db:
    image: postgres:15.1
    container_name: websocket_pg
    ports:
      - "7789:5432"
    env_file: app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.0.4
    container_name: websocket_redis
    env_file: app/.env
    ports:
      - "2278:6379"
    volumes:
      - redis_data:/var/lib/redis/data/


  app:
    build: app
    container_name: websocket_chat
    env_file: app/.env
    ports:
      - "8000:8000"
    volumes:
      - ./app/src:/websocket_chat/src
      - ./app/database:/websocket_chat/database
    command: sh -c "alembic upgrade head && uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - db
      - redis



volumes:
  postgres_data:
  redis_data:
